### ISSUE TITLE
Could not build app

### ISSUE THREAD

**Issue by Ombrelin** [pietersartain/shiori-android-app#1]
Hello, 
I tried to build the app with Andoird Studio (v4.1.1) and Gradle Sync throws :
> Task 'wrapper' not found in project ':app'.

Do you have any idea of what culd have gone wrong ?

Thank you in advance

**Comment by pietersartain** [comment]
@Ombrelin I'm so sorry I missed this from you! I have turned on my emails notifications from github now (I hope). You can always poke me on email as well, my address is on my github page.

Really sorry to say that "it works for me", however a few questions for you:

 * What platform you are building on? Windows, MacOS or Linux?
 * Can you get anything to build? An example project or similar?

I originally wrote this on MacOS Android Studio 3.something. I've just downloaded Android Studio 4.1.2 on Windows, checked out the repo using the GitHub client and it built fine. I can't check the app function with the emulator right now (nested virtualisation) but the project has built okay.

Some things that I found were important:

 * When you open the project, ensure that you've opened the whole git repo, not just the app folder within the repo.
 * Wait while the project is rescanned and loaded properly (so you shouldn't just have a file list, it should be a structured project)
 *  Ensure you've checked out the subproject to Volley as well.
 * Ignore Android Studio's request to update Gradle.
 * Make sure you've got your SDKs and VMs installed and configured or it will complain about licenses

Embedded systems development generally can be a bit of a challenge with the number of moving parts involved, but the Android ecosystem is one of the better ones, once everything is setup and working.

I hope that helps, let me know how you get on!

**Comment by Ombrelin** [comment]
Okay I tried again and I think your "Ignore Android Studio's request to update Gradle" advice solved my problem. 
I was able to compile and install the app, I will use it with my Shiori instance. Thank you for your time spent making this and for your help !
