### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by CattopyTheWeb** [pietersartain/shiori-android-app#4]
Where can I download just the APK file?

**Comment by CattopyTheWeb** [comment]
@pietersartain

**Comment by pietersartain** [comment]
Hey @CattopyTheWeb I don't have a download available. The build instructions are listed on the readme, but may need updating now. If you'd like to look at turning those into a github action, pull requests welcome!

**Comment by CattopyTheWeb** [comment]
Thanks for your response.
I have never compiled an app before. Could you tell me what you did to compile it?

**Comment by CattopyTheWeb** [comment]
@pietersartain Could you please help me build it?
